//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAppWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAllergy
    {
        public int AllergyID { get; set; }
        public int PatientID { get; set; }
        public string Allergy { get; set; }
        public System.DateTime IdentifiedOn { get; set; }
        public string Comment { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
