//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAppWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
            this.PatientVitals = new HashSet<PatientVital>();
            this.PatientAllergies = new HashSet<PatientAllergy>();
            this.PatientInsurances = new HashSet<PatientInsurance>();
            this.PatientMedications = new HashSet<PatientMedication>();
        }
    
        public int PatientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public System.DateTime DOB { get; set; }
        public string SSN { get; set; }
        public string Gender { get; set; }
        public Nullable<int> ImageId { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<PatientVital> PatientVitals { get; set; }
        public virtual ICollection<PatientAllergy> PatientAllergies { get; set; }
        public virtual ICollection<PatientInsurance> PatientInsurances { get; set; }
        public virtual ICollection<PatientMedication> PatientMedications { get; set; }
    }
}
