//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAppWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInsurance
    {
        public int ID { get; set; }
        public int PatientID { get; set; }
        public string InsuranceProvider { get; set; }
        public string Type { get; set; }
        public double CoPay { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public string InsuranceProviderDetail { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
