//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAppWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedication
    {
        public int MedicationID { get; set; }
        public int PatientID { get; set; }
        public string Name { get; set; }
        public string Dosage { get; set; }
        public string HowOftenTaken { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
